name: commander_console
description: Tactical C2 Dashboard
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  audioplayers: ^6.0.0
  permission_handler: ^11.0.0
  wakelock_plus: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/connect.mp3
    - assets/sounds/order.mp3
    - assets/sounds/alert.mp3
    - assets/logo.png